export const SECTION_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  auctions: "Live auctions",
  "access-codes": "Access code requests",
  listings: "Listing approvals",
  disputes: "Disputes",
  users: "Users & wallets",
  mechanics: "Mechanics",
  payments: "Payments & ledger",
  withdrawals: "Withdrawal authorization",
  settlements: "Settlements",
  notifications: "Notifications log",
  health: "System health",
  settings: "Settings",
};
