import type { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1777155753715 implements MigrationInterface {
    name = 'AutoMigration1777155753715'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_refresh_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "listing_access_applications" DROP CONSTRAINT "FK_listing_access_applications_user"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_notification_preferences_user"`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" DROP CONSTRAINT "FK_user_listing_permissions_user"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" DROP CONSTRAINT "FK_wallet_ledger_entries_wallet"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_wallets_user"`);
        await queryRunner.query(`ALTER TABLE "wallet_holds" DROP CONSTRAINT "FK_wallet_holds_wallet"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" DROP CONSTRAINT "FK_wallet_withdrawals_user"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" DROP CONSTRAINT "FK_wallet_withdrawals_wallet"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" DROP CONSTRAINT "FK_wallet_funding_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" DROP CONSTRAINT "FK_wallet_funding_accounts_wallet"`);
        await queryRunner.query(`ALTER TABLE "upload_assets" DROP CONSTRAINT "FK_upload_assets_owner"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_notification_reads_user"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_notification_reads_notification"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_recipient"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_auctions_settled_by"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_auctions_seller"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_bids_wallet_hold"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_bids_bidder"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_bids_auction"`);
        await queryRunner.query(`ALTER TABLE "payment_account_settings" DROP CONSTRAINT "FK_payment_account_settings_updated_by"`);
        await queryRunner.query(`ALTER TABLE "bidding_settings" DROP CONSTRAINT "FK_bidding_settings_updated_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_user_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_listing_access_applications_pending"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_ledger_entries_wallet_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_holds_wallet_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_withdrawals_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_funding_accounts_user_provider"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_upload_assets_owner_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_reads_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_recipient_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_admin_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gadget_listings_lister_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gadget_listings_pending"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_car_listings_active_registration"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_car_listings_lister_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_car_listings_pending"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_auctions_status_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_auctions_category_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bids_auction_amount"`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" DROP CONSTRAINT "UQ_user_listing_permissions_user_category"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "UQ_auctions_category_listing"`);
        await queryRunner.query(`CREATE TABLE "watchlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "auctionId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c2168300f3352178a917cd8852b" UNIQUE ("userId", "auctionId"), CONSTRAINT "PK_0c8c0dbcc8d379117138e71ad5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_status_enum" AS ENUM('PAYMENT_CONFIRMED', 'SELLER_SHIPS', 'INSPECTION', 'DISPATCH', 'DELIVERED')`);
        await queryRunner.query(`CREATE TABLE "auction_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auctionId" uuid NOT NULL, "winnerId" uuid NOT NULL, "sellerId" uuid NOT NULL, "status" "public"."delivery_status_enum" NOT NULL DEFAULT 'PAYMENT_CONFIRMED', "trackingInfo" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bd785a7a67c9b5eb83b60c2ae10" UNIQUE ("auctionId"), CONSTRAINT "REL_bd785a7a67c9b5eb83b60c2ae1" UNIQUE ("auctionId"), CONSTRAINT "PK_97f7f4616c79364db609002a99b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD "emailEnabled" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD "pushEnabled" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('INDIVIDUAL_BIDDER', 'CAR_DEALER', 'MECHANIC', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'INDIVIDUAL_BIDDER'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."wallet_ledger_type_enum" RENAME TO "wallet_ledger_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_type_enum" AS ENUM('WALLET_FUNDING_CONFIRMED', 'WITHDRAWAL_REQUESTED', 'WITHDRAWAL_FAILED', 'WITHDRAWAL_CONFIRMED', 'BID_HOLD_CREATED', 'BID_HOLD_RELEASED', 'BID_HOLD_APPLIED', 'BID_HOLD_FORFEITED', 'FINAL_PAYMENT_CONFIRMED', 'ADMIN_ADJUSTMENT')`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" ALTER COLUMN "type" TYPE "public"."wallet_ledger_type_enum" USING "type"::"text"::"public"."wallet_ledger_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum" RENAME TO "payment_provider_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum" AS ENUM('MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum" USING "provider"::"text"::"public"."payment_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" SET DEFAULT 'MONNIFY'`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" SET DEFAULT 'MONNIFY'`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum" RENAME TO "payment_provider_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum" AS ENUM('MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum" USING "provider"::"text"::"public"."payment_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" SET DEFAULT 'MONNIFY'`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" SET DEFAULT 'MONNIFY'`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum" RENAME TO "payment_provider_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum" AS ENUM('MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "payment_webhook_events" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum" USING "provider"::"text"::"public"."payment_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" ADD CONSTRAINT "UQ_74f46b87023a0a367fb88957456" UNIQUE ("userId", "category")`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listing_access_applications" ADD CONSTRAINT "FK_3d5e9a393521d0008d926258a8b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_b70c44e8b00757584a393225593" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" ADD CONSTRAINT "FK_8163240c1ae21327f8d262148f1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" ADD CONSTRAINT "FK_8e50f3f4425d99d4060af1888bc" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_holds" ADD CONSTRAINT "FK_c8808feb3594ff772bed78cc958" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ADD CONSTRAINT "FK_ad29fd88b669636c93be6274019" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ADD CONSTRAINT "FK_44911cee57611df0cf92725288f" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchlist" ADD CONSTRAINT "FK_03878f3f177c680cc195900f80a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_assets" ADD CONSTRAINT "FK_62cf566a7208368baa320d85bf9" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_38d077b9c1f597ae662c5ae4119" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_bddd24aed9c7f0beee6e8d8339f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_6d6b20987ed2f61e8801398f8d1" FOREIGN KEY ("auctionId") REFERENCES "auctions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_deliveries" ADD CONSTRAINT "FK_bd785a7a67c9b5eb83b60c2ae10" FOREIGN KEY ("auctionId") REFERENCES "auctions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auction_deliveries" DROP CONSTRAINT "FK_bd785a7a67c9b5eb83b60c2ae10"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_6d6b20987ed2f61e8801398f8d1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_bddd24aed9c7f0beee6e8d8339f"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_38d077b9c1f597ae662c5ae4119"`);
        await queryRunner.query(`ALTER TABLE "upload_assets" DROP CONSTRAINT "FK_62cf566a7208368baa320d85bf9"`);
        await queryRunner.query(`ALTER TABLE "watchlist" DROP CONSTRAINT "FK_03878f3f177c680cc195900f80a"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" DROP CONSTRAINT "FK_44911cee57611df0cf92725288f"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" DROP CONSTRAINT "FK_ad29fd88b669636c93be6274019"`);
        await queryRunner.query(`ALTER TABLE "wallet_holds" DROP CONSTRAINT "FK_c8808feb3594ff772bed78cc958"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" DROP CONSTRAINT "FK_8e50f3f4425d99d4060af1888bc"`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" DROP CONSTRAINT "FK_8163240c1ae21327f8d262148f1"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_b70c44e8b00757584a393225593"`);
        await queryRunner.query(`ALTER TABLE "listing_access_applications" DROP CONSTRAINT "FK_3d5e9a393521d0008d926258a8b"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" DROP CONSTRAINT "UQ_74f46b87023a0a367fb88957456"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum_old" AS ENUM('OPAY', 'MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "payment_webhook_events" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum_old" USING "provider"::"text"::"public"."payment_provider_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum_old" RENAME TO "payment_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum_old" AS ENUM('OPAY', 'MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum_old" USING "provider"::"text"::"public"."payment_provider_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum_old" RENAME TO "payment_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."payment_provider_enum_old" AS ENUM('OPAY', 'MONNIFY')`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ALTER COLUMN "provider" TYPE "public"."payment_provider_enum_old" USING "provider"::"text"::"public"."payment_provider_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payment_provider_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_provider_enum_old" RENAME TO "payment_provider_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_type_enum_old" AS ENUM('TOP_UP_INITIATED', 'TOP_UP_CONFIRMED', 'BID_HOLD_CREATED', 'BID_HOLD_RELEASED', 'BID_HOLD_APPLIED', 'BID_HOLD_FORFEITED', 'FINAL_PAYMENT_CONFIRMED', 'ADMIN_ADJUSTMENT', 'WALLET_FUNDING_CONFIRMED', 'WITHDRAWAL_REQUESTED', 'WITHDRAWAL_FAILED', 'WITHDRAWAL_CONFIRMED')`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" ALTER COLUMN "type" TYPE "public"."wallet_ledger_type_enum_old" USING "type"::"text"::"public"."wallet_ledger_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."wallet_ledger_type_enum_old" RENAME TO "wallet_ledger_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('INDIVIDUAL_BIDDER', 'CAR_DEALER', 'MECHANIC', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'INDIVIDUAL_BIDDER'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP COLUMN "pushEnabled"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP COLUMN "emailEnabled"`);
        await queryRunner.query(`DROP TABLE "auction_deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_status_enum"`);
        await queryRunner.query(`DROP TABLE "watchlist"`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "UQ_auctions_category_listing" UNIQUE ("category", "listingId")`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" ADD CONSTRAINT "UQ_user_listing_permissions_user_category" UNIQUE ("userId", "category")`);
        await queryRunner.query(`CREATE INDEX "IDX_bids_auction_amount" ON "bids" ("auctionId", "amountKobo") `);
        await queryRunner.query(`CREATE INDEX "IDX_auctions_category_start" ON "auctions" ("category", "startTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_auctions_status_start" ON "auctions" ("startTime", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_car_listings_pending" ON "car_listings" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_car_listings_lister_status" ON "car_listings" ("listerId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_car_listings_active_registration" ON "car_listings" ("registrationNumber") WHERE (status <> 'REJECTED'::listing_status_enum)`);
        await queryRunner.query(`CREATE INDEX "IDX_gadget_listings_pending" ON "gadget_listings" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_gadget_listings_lister_status" ON "gadget_listings" ("listerId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_admin_created" ON "notifications" ("audience", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_recipient_created" ON "notifications" ("recipientId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_reads_user" ON "notification_reads" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_upload_assets_owner_created" ON "upload_assets" ("ownerId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_funding_accounts_user_provider" ON "wallet_funding_accounts" ("userId", "provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_withdrawals_user_created" ON "wallet_withdrawals" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_holds_wallet_status" ON "wallet_holds" ("walletId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_ledger_entries_wallet_created" ON "wallet_ledger_entries" ("walletId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_listing_access_applications_pending" ON "listing_access_applications" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_user_active" ON "refresh_tokens" ("userId", "expiresAt") WHERE ("revokedAt" IS NULL)`);
        await queryRunner.query(`ALTER TABLE "bidding_settings" ADD CONSTRAINT "FK_bidding_settings_updated_by" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_account_settings" ADD CONSTRAINT "FK_payment_account_settings_updated_by" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_bids_auction" FOREIGN KEY ("auctionId") REFERENCES "auctions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_bids_bidder" FOREIGN KEY ("bidderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_bids_wallet_hold" FOREIGN KEY ("walletHoldId") REFERENCES "wallet_holds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_auctions_seller" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_auctions_settled_by" FOREIGN KEY ("settledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_recipient" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_notification_reads_notification" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_notification_reads_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_assets" ADD CONSTRAINT "FK_upload_assets_owner" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ADD CONSTRAINT "FK_wallet_funding_accounts_wallet" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_funding_accounts" ADD CONSTRAINT "FK_wallet_funding_accounts_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ADD CONSTRAINT "FK_wallet_withdrawals_wallet" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_withdrawals" ADD CONSTRAINT "FK_wallet_withdrawals_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_holds" ADD CONSTRAINT "FK_wallet_holds_wallet" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_wallets_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger_entries" ADD CONSTRAINT "FK_wallet_ledger_entries_wallet" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_listing_permissions" ADD CONSTRAINT "FK_user_listing_permissions_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_notification_preferences_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listing_access_applications" ADD CONSTRAINT "FK_listing_access_applications_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_refresh_tokens_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
