import type { Auction, MyBid, ActivityEntry, Notif } from "./types";

const MIN = 60 * 1000;
const HOUR = 60 * MIN;

export const AUCTIONS: Auction[] = [
  {
    id: "a-4471",
    title: "iPhone 15 Pro Max · 256GB",
    cat: "gadgets",
    meta: "Sealed · Natural Titanium",
    start: 450_000,
    current: 985_000,
    bids: 47,
    ends: Date.now() + 42 * MIN + 18_000,
    live: true,
    location: "Ikoyi, Lagos",
    seller: "BidNaija Official",
    photos: 6,
    highlights: ["Factory sealed", "1 year Apple warranty", "Verified IMEI"],
  },
  {
    id: "a-4468",
    title: "2019 Toyota Camry SE",
    cat: "cars",
    meta: "68k km · 2.5L I4 · Automatic",
    start: 8_500_000,
    current: 12_800_000,
    bids: 23,
    ends: Date.now() + 3 * HOUR + 12 * MIN,
    live: true,
    location: "Lekki, Lagos",
    seller: "Moses O.",
    photos: 14,
    highlights: [
      "Clean Lagos papers",
      "3rd party insurance",
      "Accident-free report",
    ],
  },
  {
    id: "a-4472",
    title: 'MacBook Pro 14" M3 Pro',
    cat: "gadgets",
    meta: "18GB · 512GB · Space Black",
    start: 1_200_000,
    current: 1_850_000,
    bids: 18,
    ends: Date.now() + 5 * HOUR,
    live: true,
    location: "Victoria Island",
    seller: "Tech Souq",
    photos: 8,
  },
  {
    id: "a-4475",
    title: "2016 Honda Accord EX-L",
    cat: "cars",
    meta: "112k km · V6 · Leather",
    start: 6_200_000,
    current: 6_200_000,
    bids: 0,
    ends: Date.now() + 19 * HOUR,
    live: false,
    location: "Abuja",
    seller: "Kemi Auto",
    photos: 11,
  },
  {
    id: "a-4480",
    title: "Samsung Galaxy S24 Ultra",
    cat: "gadgets",
    meta: "512GB · Titanium Violet",
    start: 650_000,
    current: 0,
    bids: 0,
    ends: Date.now() + 26 * HOUR,
    live: false,
    location: "Port Harcourt",
    seller: "BidNaija Official",
    photos: 5,
  },
  {
    id: "a-4482",
    title: "2018 Lexus RX 350",
    cat: "cars",
    meta: "84k km · AWD · F-Sport",
    start: 18_000_000,
    current: 0,
    bids: 0,
    ends: Date.now() + 38 * HOUR,
    live: false,
    location: "Ikeja GRA",
    seller: "Lexus Motors",
    photos: 16,
  },
];

export const MY_BIDS: MyBid[] = [
  { id: "a-4471", status: "leading", myBid: 985_000, topBid: 985_000 },
  { id: "a-4468", status: "outbid", myBid: 12_500_000, topBid: 12_800_000 },
  { id: "a-4472", status: "leading", myBid: 1_850_000, topBid: 1_850_000 },
  { id: "a-4475", status: "scheduled", myBid: null, topBid: null },
];

export const ACTIVITY: ActivityEntry[] = [
  {
    id: 1,
    type: "hold",
    title: "Hold placed",
    sub: "iPhone 15 Pro Max · 10% of ₦985,000",
    amt: -98_500,
    time: "15:38",
  },
  {
    id: 2,
    type: "release",
    title: "Hold released",
    sub: "Honda Accord · outbid",
    amt: 620_000,
    time: "14:12",
  },
  {
    id: 3,
    type: "top",
    title: "Wallet top-up",
    sub: "Paystack · card ending 4412",
    amt: 500_000,
    time: "Yesterday",
  },
  {
    id: 4,
    type: "hold",
    title: "Hold placed",
    sub: "Toyota Camry · 10% of ₦12,500,000",
    amt: -1_250_000,
    time: "Yesterday",
  },
  {
    id: 5,
    type: "pay",
    title: "Auction settled",
    sub: "iPad Pro · balance paid",
    amt: -740_000,
    time: "3 days ago",
  },
  {
    id: 6,
    type: "top",
    title: "Wallet top-up",
    sub: "Bank transfer · GTBank",
    amt: 2_000_000,
    time: "3 days ago",
  },
];

export const NOTIFS: Notif[] = [
  {
    id: 1,
    kind: "alert",
    title: "You were outbid",
    desc: "Toyota Camry SE — new top bid ₦12,800,000. Your hold will be released if you don't counter.",
    time: "2m",
    unread: true,
  },
  {
    id: 2,
    kind: "bid",
    title: "You're leading",
    desc: "iPhone 15 Pro Max at ₦985,000. 41 minutes left.",
    time: "12m",
    unread: true,
  },
  {
    id: 3,
    kind: "wa",
    title: "WhatsApp reminder sent",
    desc: "Lexus RX 350 opens in 2 hours. Reply STOP to mute.",
    time: "1h",
    unread: false,
  },
  {
    id: 4,
    kind: "email",
    title: "Hold released",
    desc: "Honda Accord outbid — ₦620,000 returned to available balance.",
    time: "3h",
    unread: false,
  },
  {
    id: 5,
    kind: "email",
    title: "Access code delivered",
    desc: "Your monthly Ready-to-Bid code is active until 30 Apr.",
    time: "2d",
    unread: false,
  },
];

export const WALLET_BALANCE = 1_245_800;
export const WALLET_HOLD = 1_348_500;
